In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F 
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [3]:
%%time
start = time.time()
zeros = torch.zeros(1, 1)
end = time.time()
elapsed = end - start
print(f"{elapsed:.10f}")

0.0120007992
CPU times: total: 0 ns
Wall time: 13 ms


In [4]:
trand1 = torch.rand(100, 100, 100, 100).to(device)
trand2 = torch.rand(100, 100, 100, 100).to(device)
nrand1 = torch.rand(100, 100, 100, 100)
nrand2 = torch.rand(100, 100, 100, 100)
start = time.time()
rand = (trand1 @ trand2)
end = time.time()
elapsed = end - start
print(f"{elapsed:.8f}")
start = time.time()
rand = np.multiply(nrand1, nrand2)
end = time.time()
elapsed = end - start
print(f"{elapsed:.8f}")

0.22505331
0.13252544


In [5]:
probablity = torch.tensor([.1, .9])
samples = torch.multinomial(probablity, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 0, 1, 1, 1])


In [6]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [7]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [8]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [9]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [10]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [11]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [12]:
ten1 = torch.tensor([1, 2, 3])
ten2 = torch.tensor([4, 5, 6])
ten3 = torch.tensor([7, 8, 9])
stacked_tensor = torch.stack([ten1, ten2, ten3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([12.7185, -6.1500,  9.2635], grad_fn=<SqueezeBackward4>)


In [14]:
ten1 = torch.tensor([1., 2., 3.])
out = F.softmax(ten1, dim=0)
print(out)

tensor([0.0900, 0.2447, 0.6652])


In [15]:
vocab = 1000
embed = 8
embedding = nn.Embedding(vocab, embed)
input = torch.LongTensor([1, 5, 3, 2])
out = embedding(input)
print(out.shape)
print(out)

torch.Size([4, 8])
tensor([[ 0.6451, -0.2020, -1.0945, -1.4386, -0.3137,  0.7476,  0.6285, -0.7892],
        [-0.5685,  0.9658,  0.3709, -0.8021,  0.0103, -0.1492,  0.4547, -0.4272],
        [-1.1851,  1.9537,  1.7965,  1.1024, -1.4032,  0.1104, -0.5551, -0.0763],
        [ 1.1218, -0.0259, -0.8936,  1.6492, -0.0232,  0.7713, -0.0474,  0.8120]],
       grad_fn=<EmbeddingBackward0>)


In [16]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [17]:
i64 = torch.randint(1, (3, 2)).float()
f32 = torch.rand(2, 3)
print(i64.dtype, f32.dtype)
res = torch.matmul(i64, f32)
print(res)

torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [22]:
a = torch.rand(2, 3, 5)
print(a.shape)
print(a)
x, y, z = a.shape
a = a.view(x*y, z)
print(a.shape)
print(a)

torch.Size([2, 3, 5])
tensor([[[0.2102, 0.1068, 0.8401, 0.7850, 0.8078],
         [0.8188, 0.8560, 0.5365, 0.6834, 0.5446],
         [0.8871, 0.6639, 0.2561, 0.7277, 0.5182]],

        [[0.0882, 0.7825, 0.3658, 0.1937, 0.2096],
         [0.1175, 0.0184, 0.7250, 0.6106, 0.2157],
         [0.8308, 0.0646, 0.1275, 0.9944, 0.9517]]])
torch.Size([6, 5])
tensor([[0.2102, 0.1068, 0.8401, 0.7850, 0.8078],
        [0.8188, 0.8560, 0.5365, 0.6834, 0.5446],
        [0.8871, 0.6639, 0.2561, 0.7277, 0.5182],
        [0.0882, 0.7825, 0.3658, 0.1937, 0.2096],
        [0.1175, 0.0184, 0.7250, 0.6106, 0.2157],
        [0.8308, 0.0646, 0.1275, 0.9944, 0.9517]])
