In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F 
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [2]:
%%time
start = time.time()
zeros = torch.zeros(1, 1)
end = time.time()
elapsed = end - start
print(f"{elapsed:.10f}")

0.0149958134
CPU times: total: 0 ns
Wall time: 15 ms


In [3]:
trand1 = torch.rand(100, 100, 100, 100).to(device)
trand2 = torch.rand(100, 100, 100, 100).to(device)
nrand1 = torch.rand(100, 100, 100, 100)
nrand2 = torch.rand(100, 100, 100, 100)
start = time.time()
rand = (trand1 @ trand2)
end = time.time()
elapsed = end - start
print(f"{elapsed:.8f}")
start = time.time()
rand = np.multiply(nrand1, nrand2)
end = time.time()
elapsed = end - start
print(f"{elapsed:.8f}")

0.24733424
0.13961864


In [4]:
probablity = torch.tensor([.1, .9])
samples = torch.multinomial(probablity, num_samples=10, replacement=True)
print(samples)

tensor([1, 0, 1, 1, 0, 1, 1, 1, 1, 1])


In [5]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [6]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [8]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [9]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [10]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [11]:
ten1 = torch.tensor([1, 2, 3])
ten2 = torch.tensor([4, 5, 6])
ten3 = torch.tensor([7, 8, 9])
stacked_tensor = torch.stack([ten1, ten2, ten3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-1.3205,  1.4535,  4.4861], grad_fn=<SqueezeBackward4>)


In [13]:
ten1 = torch.tensor([1., 2., 3.])
out = F.softmax(ten1, dim=0)
print(out)

tensor([0.0900, 0.2447, 0.6652])


In [14]:
vocab = 1000
embed = 8
embedding = nn.Embedding(vocab, embed)
input = torch.LongTensor([1, 5, 3, 2])
out = embedding(input)
print(out.shape)
print(out)

torch.Size([4, 8])
tensor([[-0.0065,  0.8686,  1.6134, -0.3009, -0.1149,  0.4745,  0.8175,  0.1936],
        [ 0.1491, -3.4593,  0.5249, -0.1264, -0.0530, -1.0339, -0.0379,  1.5395],
        [ 0.0112, -0.1906, -2.2685, -0.9278, -0.1543, -0.3940, -0.9399,  0.9514],
        [-0.0190, -1.1533, -0.2111, -0.8437,  0.3561, -1.3188, -0.2643, -1.6077]],
       grad_fn=<EmbeddingBackward0>)


In [15]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [16]:
i64 = torch.randint(1, (3, 2)).float()
f32 = torch.rand(2, 3)
print(i64.dtype, f32.dtype)
res = torch.matmul(i64, f32)
print(res)

torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [17]:
a = torch.rand(2, 3, 5)
print(a.shape)
print(a)
x, y, z = a.shape
a = a.view(x*y, z)
print(a.shape)
print(a)

torch.Size([2, 3, 5])
tensor([[[0.1639, 0.9550, 0.9564, 0.7485, 0.6014],
         [0.4513, 0.2046, 0.5394, 0.7911, 0.4087],
         [0.6055, 0.8245, 0.9491, 0.3383, 0.4762]],

        [[0.3383, 0.8992, 0.1112, 0.5898, 0.3059],
         [0.5352, 0.5104, 0.1027, 0.2389, 0.4072],
         [0.8063, 0.6635, 0.0571, 0.0021, 0.9665]]])
torch.Size([6, 5])
tensor([[0.1639, 0.9550, 0.9564, 0.7485, 0.6014],
        [0.4513, 0.2046, 0.5394, 0.7911, 0.4087],
        [0.6055, 0.8245, 0.9491, 0.3383, 0.4762],
        [0.3383, 0.8992, 0.1112, 0.5898, 0.3059],
        [0.5352, 0.5104, 0.1027, 0.2389, 0.4072],
        [0.8063, 0.6635, 0.0571, 0.0021, 0.9665]])


In [18]:
x = torch.arange(-5., 5., step=.5)
y = F.tanh(x)
print(y)

tensor([-0.9999, -0.9998, -0.9993, -0.9982, -0.9951, -0.9866, -0.9640, -0.9051,
        -0.7616, -0.4621,  0.0000,  0.4621,  0.7616,  0.9051,  0.9640,  0.9866,
         0.9951,  0.9982,  0.9993,  0.9998])
