In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F 
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [2]:
%%time
start = time.time()
zeros = torch.zeros(1, 1)
end = time.time()
elapsed = end - start
print(f"{elapsed:.10f}")

0.0000000000
CPU times: total: 0 ns
Wall time: 0 ns


In [3]:
trand1 = torch.rand(100, 100, 100, 100).to(device)
trand2 = torch.rand(100, 100, 100, 100).to(device)
nrand1 = torch.rand(100, 100, 100, 100)
nrand2 = torch.rand(100, 100, 100, 100)
start = time.time()
rand = (trand1 @ trand2)
end = time.time()
elapsed = end - start
print(f"{elapsed:.8f}")
start = time.time()
rand = np.multiply(nrand1, nrand2)
end = time.time()
elapsed = end - start
print(f"{elapsed:.8f}")

0.16208363
0.12104344


In [4]:
probablity = torch.tensor([.1, .9])
samples = torch.multinomial(probablity, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 0, 1])


In [5]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [6]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [7]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [8]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [9]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [10]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [11]:
ten1 = torch.tensor([1, 2, 3])
ten2 = torch.tensor([4, 5, 6])
ten3 = torch.tensor([7, 8, 9])
stacked_tensor = torch.stack([ten1, ten2, ten3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-8.8483,  2.9875, -6.2218], grad_fn=<SqueezeBackward4>)


In [13]:
ten1 = torch.tensor([1., 2., 3.])
out = F.softmax(ten1, dim=0)
print(out)

tensor([0.0900, 0.2447, 0.6652])


In [14]:
vocab = 1000
embed = 8
embedding = nn.Embedding(vocab, embed)
input = torch.LongTensor([1, 5, 3, 2])
out = embedding(input)
print(out.shape)
print(out)

torch.Size([4, 8])
tensor([[ 6.2203e-01, -8.2601e-03, -3.5325e-01,  1.0020e+00, -2.5921e+00,
         -4.1420e-02, -7.6367e-01, -1.5360e-01],
        [-1.7146e-01,  7.8410e-02, -1.5409e+00, -1.4448e+00, -3.7338e-01,
          1.4872e+00,  1.3994e+00,  8.5873e-01],
        [ 4.5658e-01,  7.3903e-02, -1.2910e+00,  1.6170e+00, -8.8788e-01,
          9.7241e-01, -3.6466e-01, -2.3339e-03],
        [ 8.7553e-01,  3.7886e-01, -7.2948e-01,  9.2928e-01, -6.4227e-01,
         -1.1786e+00,  7.8466e-02, -2.3366e+00]], grad_fn=<EmbeddingBackward0>)


In [15]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [16]:
i64 = torch.randint(1, (3, 2)).float()
f32 = torch.rand(2, 3)
print(i64.dtype, f32.dtype)
res = torch.matmul(i64, f32)
print(res)

torch.float32 torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [17]:
a = torch.rand(2, 3, 5)
print(a.shape)
print(a)
x, y, z = a.shape
a = a.view(x*y, z)
print(a.shape)
print(a)

torch.Size([2, 3, 5])
tensor([[[0.9309, 0.5197, 0.0013, 0.8468, 0.3222],
         [0.5446, 0.2379, 0.4932, 0.8868, 0.7812],
         [0.3097, 0.6755, 0.9722, 0.6072, 0.6038]],

        [[0.9825, 0.6071, 0.3450, 0.2446, 0.6275],
         [0.1203, 0.8036, 0.0254, 0.4499, 0.7691],
         [0.5650, 0.2991, 0.5386, 0.5061, 0.5951]]])
torch.Size([6, 5])
tensor([[0.9309, 0.5197, 0.0013, 0.8468, 0.3222],
        [0.5446, 0.2379, 0.4932, 0.8868, 0.7812],
        [0.3097, 0.6755, 0.9722, 0.6072, 0.6038],
        [0.9825, 0.6071, 0.3450, 0.2446, 0.6275],
        [0.1203, 0.8036, 0.0254, 0.4499, 0.7691],
        [0.5650, 0.2991, 0.5386, 0.5061, 0.5951]])


In [22]:
x = torch.arange(-5., 5., step=.5)
y = F.sigmoid(x)
print(y)

tensor([0.0067, 0.0110, 0.0180, 0.0293, 0.0474, 0.0759, 0.1192, 0.1824, 0.2689,
        0.3775, 0.5000, 0.6225, 0.7311, 0.8176, 0.8808, 0.9241, 0.9526, 0.9707,
        0.9820, 0.9890])
